# Generated by Django 5.1.2 on 2024-10-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_date_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
