# Generated by Django 5.1.2 on 2024-11-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="post",
            name="date_publish",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
