# Generated by Django 5.1.2 on 2024-11-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_weathercondition_area_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeatherCondition",
        ),
    ]
